### ISSUE TITLE
Window resize events are flooding the breadcrumbs log

### ISSUE THREAD

**Issue by maBarabas** [getsentry/sentry-dart#1926] opened 2024-03-08 16:11 UTC
### Platform

Flutter Desktop

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

```
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.19045.4046], locale en-GB)
    • Flutter version 3.16.0 on channel stable at C:\Users\barabas\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)              
    • Android SDK at C:\Users\barabas\AppData\Local\Android\sdk                               
    X cmdline-tools component is missing                                                      
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`                               
      See https://developer.android.com/studio/command-line for more details.                 
    X Android license status unknown.                                                         
      Run `flutter doctor --android-licenses` to accept the SDK licenses.                     
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
                                                                                              
[√] Chrome - develop for the web                                                              
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.53
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.66

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

### Version

7.13.2

### Steps to Reproduce

1. Integrate sentry with the app
2. Resive the window
3. Submit an event (`Sentry.captureMessage`)

### Expected Result

Some resize breadcrumbs are visible, other breadcrumbs also visible

### Actual Result

hundreds of resive events are added within a second, can't find other breadcrumbs in the noise

The window resize events should be debounced at a rate of 1 per second or so.

### Are you willing to submit a PR?

No

**Comment by ueman** [comment] 2024-03-11 06:25
This seems like a duplicate of https://github.com/getsentry/sentry-dart/issues/400

**Closed as not planned** 2024-03-11 09:04 UTC
Labels: Bug
