### ISSUE TITLE
in Sentry client no option to add connectionTimeout But the normal http package has this option , How can we add connection Timeout to the client ?

### ISSUE THREAD

**Issue by harishkthedeveloper** [getsentry/sentry-dart#1221] opened 2023-01-12 12:35 UTC
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

I have the following issue:

in Sentry client no option to add connectionTimeout But the normal http package has this option , How can we add connection Timeout to the client ?

i want connection timeout 

`final client = new HttpClient();
client.connectionTimeout = const Duration(seconds: 5);
`
normal timeout is there in sentry client which only throws TimeoutException,  but i need SocketException to be thrown when the server is not reachable within connectionTimeout period.

**Comment by marandaneto** [comment] 2023-01-12 12:45
Dupe of https://github.com/getsentry/sentry-dart/issues/1149 and https://github.com/getsentry/sentry-dart/issues/392

**Closed as completed by marandaneto** 2023-01-12 12:45 UTC
Labels: Bug

**Comment by harishkthedeveloper** [comment] 2023-01-13 10:08
This did not answer my question.. for sentry we are not able to set connectionTimeOut

**Comment by marandaneto** [comment] 2023-01-13 10:21
It's not currently possible, hence the 2 linked issues.
