### ISSUE TITLE
Capture the device's thermal state

### ISSUE THREAD

**Issue by ahmdaeyz** [getsentry/sentry-dart#1552] opened 2023-07-14 21:11 UTC
### Problem Statement

As a user, I'd want to see the customer's device's thermal state as part of the events I get in the dashboard. These can also be treated as App hangs and have their separate events.

### Solution Brainstorm

I have written a small plugin that gets an iOS device's current thermal state and it subscribes to thermal state changes and sends the events to Flutter (it uses ProcessInfo just like the Apple docs say). I'm sure this will be trivial in Android. I'm confused about where some events come from because of the flags that control native performance reporting. So I don't know if this should be the responsibility of Flutter or Android and iOS SDKs. 

### Are you willing to submit a PR?

Yes

**Comment by marandaneto** [comment] 2023-07-17 08:10
@ahmdaeyz Thanks for your message.

Do you mean something like https://source.android.com/docs/core/power/thermal-mitigation#thermal-api ?

We already collect the device temperature as well https://github.com/getsentry/sentry-java/blob/3baa73f8cb421d911d8606916fa0945193251178/sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java#L471-L481

Is your plugin on GitHub? can you share the link so we can take a look?

Thanks.

**Comment by marandaneto** [comment] 2023-07-17 08:12
Also, what's the relation between the thermal state and app hangs?
I see the thermal state as extra metadata, but part of a thrown error, while the app hangs, is its own error.

**Comment by marandaneto** [comment] 2023-07-26 10:19
@ahmdaeyz any feedback on the questions above?

**Comment by ahmdaeyz** [comment] 2023-08-06 10:19
Hey @marandaneto 
I'm sorry for my late reply. For some reason I can't see the temperature in the dashboard. Maybe it is sent on certain events with a logic behind it? Where is it supposed to show up? 

What I meant with 
> These can also be treated as App hangs and have their separate events

I meant treat it just like app hangs, When the device thermal state of the user reaches a critical state it might be reasonable to log it so that If the app is getting hot on users device the developer get notified and fix it.

I will try to push my thermal plugin code to Github and link you to it.

**Comment by marandaneto** [comment] 2023-08-07 08:10
<img width="366" alt="Screenshot 2023-08-07 at 10 07 05" src="https://github.com/getsentry/sentry-dart/assets/5731772/f4c472c3-091f-420c-8be2-6edeb915b6ff">

It's part of the Device context on the Issue details page.
https://your_org.sentry.io/issues/?project=your_project -> eg click on any Android issue, it should be a real device with temperature capabilities.

I don't think it's a good idea to raise an event if the device's thermal state is hot since it can be caused by any other app or even the OS, leading to a lot of false-positive/noise.

Tag me and I can take a look, thanks for raising this, closing it for now.

**Closed as completed by marandaneto** 2023-08-07 08:10 UTC
