### ISSUE TITLE
Update uuid version

### ISSUE THREAD

**Issue by EnvOut** [getsentry/sentry-dart#1644] opened 2023-09-18 09:09 UTC
### Problem Statement

I need uuid's v7 and this requires uuid: ^4.0.0
But sentry and sentry_flutter still use: ^3.0.0

Please update uuid version

### Solution Brainstorm

Please update uuid version from ^3.0.0 to ^4.0.0

### Are you willing to submit a PR?

None

**Comment by vaind** [comment] 2023-09-18 11:00
duplicate of #1623

**Closed as not planned by vaind** 2023-09-18 11:00 UTC
Labels: Waiting for: Product Owner
