### ISSUE TITLE
D/Sentry  (22979): UncaughtExceptionHandlerIntegration removed. - How to handle

### ISSUE THREAD

**Issue by rabi-palmtree** [getsentry/sentry-dart#638] opened 2021-11-19 08:49 UTC
_Platform:_
- [ ]  Dart
- [✔]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [✔]  Other, which one? Android Studio

_Platform installed with:_
- [✔ ] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 18.04.4 LTS 5.4.0-90-generic, locale en_IN)
    • Flutter version 2.5.3 at /home/rabi/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/rabi/Android/Sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = /home/rabi/Android/Sdk
    • ANDROID_SDK_ROOT = /home/rabi/Android/Sdk
    • Java binary at: /home/rabi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/rabi/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:
On Initalizing App with Sentry, seeing the following output on emulator console

D/Sentry  (22979): UncaughtExceptionHandlerIntegration removed.
W/pool-14-thread-(22979): type=1400 audit(0.0:112): avc: denied { read } for name="version" dev="proc" ino=4026532035 scontext=u:r:untrusted_app:s0:c134,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.sentry_project_name

Is this an issue,  google search indicates this UncaughtExceptionHandlerIntegration should be installed by default. 

Also What is causing this? Could not find anything in documentation

avc: **denied { read }** for name="version" dev="proc" ino=4026532035 scontext=u:r:**untrusted_app**:s0

**Comment by marandaneto** [comment] 2021-11-19 09:20
@rabi-palmtree are you calling `Sentry.close()` at any given moment?

**Comment by rabi-palmtree** [comment] 2021-11-19 10:25
@marandaneto  Thanks for the quick response.

No calls to Sentry.close()

Only code to Sentry API is the following in main.dart

```
await SentryFlutter.init(
        (options) {
      options.dsn = _sentryDsn;
      options.tracesSampleRate = 1.0;
      options.reportPackages = false;
    },
    // Init  App.
    appRunner: () =>  runApp(MyAppPage(flutterI18nDelegate))
  );


```

**Comment by marandaneto** [comment] 2021-11-19 14:50
@rabi-palmtree can you provide me a full log of the SDK init?

Please set, `options.debug = true;` as well

**Comment by rabi-palmtree** [comment] 2021-11-20 05:38
Providing relavent logs at SDK init with options.debug=true
Anonymizing some due to this forum being public. 
Don't know why but this time UncaughtExceptionHandlerIntegration enabled: true

Launching lib/main.dart on Android SDK built for x86 in debug mode...
..
I/Sentry  ( 5174): Initializing SDK with DSN: 'https://proj_public_key.ingest.sentry.io/proj_id'
W/pool-8-thread-1( 5174): type=1400 audit(0.0:31): avc: denied { read } for name="version" dev="proc" ino=4026532035 scontext=u:r:untrusted_app:s0:c134,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.proj_package.proj_name
I/Sentry  ( 5174): GlobalHubMode: 'true'
D/Sentry  ( 5174): UncaughtExceptionHandlerIntegration enabled: true
D/Sentry  ( 5174): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
D/Sentry  ( 5174): UncaughtExceptionHandlerIntegration installed.
D/Sentry  ( 5174): ShutdownHookIntegration installed.
D/Sentry  ( 5174): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  ( 5174): NdkIntegration enabled: true
D/Sentry  ( 5174): Started processing cached files from /data/user/0/com.proj_package.proj_name/cache/sentry
D/Sentry  ( 5174): Processing dir. /data/user/0/com.proj_package.proj_name/cache/sentry
I/sentry-native( 5174): using database path "/data/data/com.proj_package.proj_name/cache/sentry/.sentry-native"
D/Sentry  ( 5174): Processing 1 items from cache dir /data/user/0/com.proj_package.proj_name/cache/sentry
D/Sentry  ( 5174): File /data/user/0/com.proj_package.proj_name/cache/sentry/outbox is not a File.
D/Sentry  ( 5174): File /data/user/0/com.proj_package.proj_name/cache/sentry/.sentry-native is not a File.
D/sentry-native( 5174): starting backend
D/Sentry  ( 5174): Processing file: /data/user/0/com.proj_package.proj_name/cache/sentry/session.json
D/Sentry  ( 5174): File '/data/user/0/com.proj_package.proj_name/cache/sentry/session.json' doesn't match extension expected.
D/Sentry  ( 5174): Processing file: /data/user/0/com.proj_package.proj_name/cache/sentry/2ee6e2e2-367c-48d5-9a85-cf37a0c40df0.envelope
D/Sentry  ( 5174): NdkIntegration installed.
D/Sentry  ( 5174): Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.proj_package.proj_name/cache/sentry/outbox
D/Sentry  ( 5174): EnvelopeFileObserverIntegration installed.
D/Sentry  ( 5174): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  ( 5174): AnrIntegration enabled: false
D/Sentry  ( 5174): enableSessionTracking enabled: true
D/Sentry  ( 5174): enableAppLifecycleBreadcrumbs enabled: true
D/Sentry  ( 5174): Captured Envelope is already cached
D/Sentry  ( 5174): AppLifecycleIntegration installed.
D/Sentry  ( 5174): ActivityLifecycleIntegration enabled: true
D/Sentry  ( 5174): ActivityLifecycleIntegration installed.
D/Sentry  ( 5174): AppComponentsBreadcrumbsIntegration enabled: true
D/Sentry  ( 5174): AppComponentsBreadcrumbsIntegration installed.
W/Sentry  ( 5174): Current session is not ended, we'd need to end it.
D/Sentry  ( 5174): SystemEventsBreadcrumbsIntegration enabled: true
D/Sentry  ( 5174): SystemEventsBreadcrumbsIntegration installed.
D/Sentry  ( 5174): enableSystemEventsBreadcrumbs enabled: true
D/Sentry  ( 5174): TempSensorBreadcrumbsIntegration installed.
D/Sentry  ( 5174): enableSystemEventBreadcrumbs enabled: true
D/Sentry  ( 5174): Serializing object: {"sid":"37c003f1-b3ba-40ae-a6e9-ebd19cdc2fca","did":"f633493b-547f-4b97-ab95-2fdf9d0bd01c","started":"2021-11-19T10:20:11.211Z","status":"exited","seq":1637385673913,"duration":68462.702,"timestamp":"2021-11-20T05:21:13.913Z","attrs":{"release":"com.proj_package.proj_name@2.0.0+1","environment":"debug"}}
D/Sentry  ( 5174): Serializing object: {"sid":"b01d94d8-9569-4745-985e-6dc3c0edd948","did":"f633493b-547f-4b97-ab95-2fdf9d0bd01c","init":true,"started":"2021-11-20T05:21:13.892Z","status":"ok","timestamp":"2021-11-20T05:21:13.892Z","attrs":{"release":"com.proj_package.proj_name@2.0.0+1","environment":"debug"}}
D/Sentry  ( 5174): Serializing object: {"sid":"b01d94d8-9569-4745-985e-6dc3c0edd948","did":"f633493b-547f-4b97-ab95-2fdf9d0bd01c","init":true,"started":"2021-11-20T05:21:13.892Z","status":"ok","timestamp":"2021-11-20T05:21:13.892Z","attrs":{"release":"com.proj_package.proj_name@2.0.0+1","environment":"debug"}}
D/Sentry  ( 5174): Adding Envelope to offline storage: /data/user/0/com.proj_package.proj_name/cache/sentry/18c16d68-46e3-4eb6-9acc-b60004cf724f.envelope
..
..
[sentry] [debug] release: com.proj_package.proj_name@2.0.0+1
..
D/Sentry  ( 5174): Envelope sent successfully.
D/Sentry  ( 5174): Discarding envelope from cache: /data/user/0/com.proj_package.proj_name/cache/sentry/18c16d68-46e3-4eb6-9acc-b60004cf724f.envelope
D/Sentry  ( 5174): Envelope flushed
..
..
D/Sentry  ( 5174): Envelope sent successfully.
D/Sentry  ( 5174): Envelope flushed
D/Sentry  ( 5174): Marking envelope submission result: true
D/Sentry  ( 5174): Deleted file /data/user/0/com.proj_package.proj_name/cache/sentry/2ee6e2e2-367c-48d5-9a85-cf37a0c40df0.envelope.
D/Sentry  ( 5174): Finished processing cached files from /data/user/0/com.proj_package.proj_name/cache/sentry
D/Sentry  ( 5174): Started processing cached files from /data/user/0/com.proj_package.proj_name/cache/sentry/outbox
D/Sentry  ( 5174): Processing dir. /data/user/0/com.proj_package.proj_name/cache/sentry/outbox
D/Sentry  ( 5174): Processing 0 items from cache dir /data/user/0/com.proj_package.proj_name/cache/sentry/outbox
D/Sentry  ( 5174): Finished processing cached files from /data/user/0/com.proj_package.proj_name/cache/sentry/outbox
..
..
..

**Comment by rabi-palmtree** [comment] 2021-11-20 07:10
Running again without options.debug=true

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,002ms.
..
D/Sentry  ( 5174): UncaughtExceptionHandlerIntegration removed.
..
I/Sentry  ( 5174): Closing SentryClient.
D/Sentry  ( 5174): Shutting down
D/Sentry  ( 5174): UncaughtExceptionHandlerIntegration enabled: true
D/Sentry  ( 5174): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
D/Sentry  ( 5174): UncaughtExceptionHandlerIntegration installed.


So this is mostly a non issue.

Can you clarify if this is  harmless:

W/pool-17-thread-( 5174): type=1400 audit(0.0:40): **avc: denied { read }** for name="version" dev="proc" ino=4026532035 scontext=u:r:**untrusted_app**:s0:c134,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=proj_package.proj_name

Thank you.

**Comment by marandaneto** [comment] 2021-11-22 09:11
@rabi-palmtree this is caused by hot restart, if the App gets restarted but the process does not die, the SDK will be initialized again and since it was initialized before, it has to be closed and initialized again.

> W/pool-17-thread-( 5174): type=1400 audit(0.0:40): avc: denied { read } for name="version" dev="proc" ino=4026532035 scontext=u:r:untrusted_app:s0:c134,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=proj_package.proj_name

this is not a Sentry's log, can't confirm if it's harmless or not.

Closing it due to not being a bug, thanks for the logs.

**Closed as completed by marandaneto** 2021-11-22 09:11 UTC
