### ISSUE TITLE
Replay: user taps crumbs have `null` message on iOS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#2341] opened 2024-10-09 14:29 UTC
### Description

The crumb `message` field seems null. And the UI/compoent requires a value.

SDK version: 8.36.0 (running on iOS)

![Image](https://github.com/user-attachments/assets/0b58922a-694f-4261-848f-1157bf15f073)

See:
* https://github.com/getsentry/sentry/issues/78837

**Comment by vaind** [comment] 2024-10-09 17:26
How did you reproduce this? I've just checked here in the flutter sample app and all looks good. 
![Image](https://github.com/user-attachments/assets/173cdd6e-caa8-44e5-8872-34a08835999f)

Interestingly, the screenshot shows "User click" while it should be "User tap".

**Comment by bruno-garcia** [comment] 2024-10-09 21:32
Not sure, this was a user event. But it wasn't a manually created breadcrumb.

**Comment by vaind** [comment] 2024-10-10 11:41
If I explicitly send nil as the message, it shows up as:
![Image](https://github.com/user-attachments/assets/60f6c55e-c93d-4d7b-a531-f5c670ee333c)

Any chance we can get (anonymized) json payload from the replay event?

**Comment by vaind** [comment] 2024-10-11 22:08
I don't believe there's anything to do in the Flutter SDK with the details we have available in the issue. At the very least, someone familiar with the UI could verify why taps are shown in breadcrumbs as clicks (if they're indeed taps)

**Comment by bruno-garcia** [comment] 2024-10-12 15:59
In that case, @c298lee I think we should merge the PR that deals with the data being null

**Comment by c298lee** [comment] 2024-10-15 06:31
There are User Click breadcrumbs and User Tap breadcrumbs. User Tap breadcrumbs have the category `user.tap` and is a mobile only breadcrumb. User Click breadcrumbs have the category `user.click` and in our UI, we expect it to have a message which contains which element was clicked. I believe this should be a web specific breadcrumb, so I'm not sure why it's showing up in a mobile replay. 

I'll repoen the PR that deals specifically with user click data being null first to resolve this issue. However, it looks like web breadcrumbs are somehow showing up in a mobile replay, and I think we should look into how that's happening. Maybe they set up custom breadcrumbs with the category `ui.click`?

**Comment by vaind** [comment] 2024-10-15 06:43
> Maybe they set up custom breadcrumbs with the category `ui.click`?

That still shouldn't get to replay because we convert all `ui.click` breadcrumbs, regardless of being set by the SDK or user, to `ui.tap` in Flutter:

https://github.com/getsentry/sentry-dart/blob/3751dbc90dc9966974f829a835778ab2de33fe54/flutter/ios/Classes/SentryFlutterReplayBreadcrumbConverter.m#L18-L42

https://github.com/getsentry/sentry-dart/blob/3751dbc90dc9966974f829a835778ab2de33fe54/flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterReplayBreadcrumbConverter.kt#L24-L51

Are we 100% sure that event is coming from Flutter? Because AFAICT, in plain cocoa SDK, the `ui.click` breadcrumb would just get passed on directly (i.e. what you've suggested might be happening)

**Comment by c298lee** [comment] 2024-10-15 14:11
From looking at the tags in the replays with these errors, it looks like they are happening on `sentry.cocoa.flutter version 8.36.0`

**Comment by vaind** [comment] 2024-11-22 12:14
As described above, this is not reproducible with the current information so I'll be closing this. Feel free to reopen if you have another idea how to reproduce this, any more details, another replay that this happened on (and we can get json data for it), etc... anything.

**Closed as not planned by vaind** 2024-11-22 12:14 UTC
