### ISSUE TITLE
Unable to build the app for Android

### ISSUE THREAD

**Issue by tomas-dorda** [getsentry/sentry-dart#1857] opened 2024-02-02 14:17 UTC
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale cs-CZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.86.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

### Version

7.15.0

### Steps to Reproduce

Try to run app for Android

### Expected Result

The app will launch

### Actual Result

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
e: file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dev/sentry_flutter-7.15.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:39:39 Unresolved reference: SentryFlutter
e: file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dev/sentry_flutter-7.15.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:49:21 Unresolved reference: SentryFlutter

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sentry_flutter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Exception: Gradle task assembleTstDebug failed with exit code 1

Exited (1).

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment] 2024-02-03 00:42
Tested it on `7.15.0` and `7.16.0` with our [example](https://github.com/getsentry/sentry-dart/tree/main/flutter/example) app, no issues here.

Looks like a cache problem?

Will try on a windows machine when I get the chance

**Comment by tomas-dorda** [comment] 2024-02-05 08:55
I've tried to run `flutter pub cache repair`  and even delete the whole cache folder but unfortunately it did not help.

**Comment by buenaflor** [comment] 2024-02-05 10:02
@denrase can you take a closer look here pls when you have time

**Comment by denrase** [comment] 2024-02-05 10:13
@tomas-dorda Interesting, It looks like the `SentryFlutterPlugin` can't find `SentryFlutter`. What does your `pubspec.yaml` look like?

**Comment by tomas-dorda** [comment] 2024-02-05 10:27
@denrase here is my pubspec.yaml

https://gist.github.com/tomas-dorda/eded82530ccacee6c7fad094f79d3cf8

**Comment by denrase** [comment] 2024-02-05 12:07
@tomas-dorda Can't see anything out of the ordinary. I will try to reproduce this on a Windows machine.

**Comment by mzdm** [comment] 2024-02-05 12:13
> @tomas-dorda Can't see anything out of the ordinary. I will try to reproduce this on a Windows machine.

This also happens on Mac. What is weird that in Codemagic pipeline in builds fine. I think it is something with debug mode probably (for me).

**Comment by denrase** [comment] 2024-02-05 12:35
@mzdm You are experiencing the same `Unresolved reference: SentryFlutter` error message on mac? Could you also post your `flutter doctor -v` output?

**Comment by mzdm** [comment] 2024-02-05 12:38
> flutter doctor -v

I work on the same project as @tomas-dorda 

```cmd
[✓] Flutter (Channel stable, 3.16.2, on macOS 13.6 22G120 darwin-arm64, locale en-CZ)
    • Flutter version 3.16.2 on channel stable at /Users/mzidek/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (10 weeks ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mzidek/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.139
    ! Error: Browsing on the local area network for sma21b634aa. Ensure the device is unlocked and attached with
      a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
    
    
```

**Comment by buenaflor** [comment] 2024-02-05 12:56
For a quick check: can you test which minimum sentry version this occurs? might be easier that way to pinpoint where this bug was introduced

**Comment by tomas-dorda** [comment] 2024-02-05 13:44
> For a quick check: can you test which minimum sentry version this occurs? might be easier that way to pinpoint where this bug was introduced

We have recently updated from these versions
```
  sentry: ^7.13.2
  sentry_dio: ^7.13.1
  sentry_flutter: ^7.13.1
  sentry_hive: ^7.13.2
  sentry_logging: ^7.13.2
```
to versions that I sent in the `pubspec.yaml` before. When I checkout commits before it works alright.

**Comment by denrase** [comment] 2024-02-05 13:47
Created a new flutter app (on mac) and imported the sentry dependencies you also have in the `pubspec.yaml`

```yaml
sentry: ^7.15.0
sentry_dio: ^7.15.0
sentry_flutter: ^7.15.0
sentry_hive: ^7.15.0
sentry_logging: ^7.15.0
```

With minimal setup:

```dart
import 'package:flutter/material.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

const String exampleDsn =
    'https://e85b375ffb9f43cf8bdf9787768149e0@o447951.ingest.sentry.io/5428562';

void main() async {
  await SentryFlutter.init((options) {
    options.dsn = exampleDsn;
  },
  appRunner: () => runApp(const MyApp())
  );
}
```

The app launches without issues on a Android emulator for me.

**Comment by denrase** [comment] 2024-02-05 14:03
@mzdm What kind of architecture is your emulator or device running on?

**Comment by tomas-dorda** [comment] 2024-02-05 14:19
I've tried it on device
![image](https://github.com/getsentry/sentry-dart/assets/33345883/3fe9252c-6b6b-403b-95ba-5a19d2731f57)
and emulator
![image](https://github.com/getsentry/sentry-dart/assets/33345883/a6e770ec-ee3b-4b8e-ae59-c906a8dca815)

**Comment by mzdm** [comment] 2024-02-05 14:38
> @mzdm What kind of architecture is your emulator or device running on?

physical, android-arm64  • Android 13 (API 33)

**Comment by buenaflor** [comment] 2024-02-05 14:55
So `7.14.0` also doesn't work?

**Comment by denrase** [comment] 2024-02-05 15:30
@mzdm I also tried now with x86_64, same result. Everything works as expected. Could you also try to create a sample app, add the sentry dependencies and init Sentry? Please report back if you are still experiencing this issue.

**Comment by mzdm** [comment] 2024-02-05 15:31
@denrase I have this NDK error, maybe it is useful ?

```
[CXX1101] NDK at /Users/mzidek/Library/Android/sdk/ndk-bundle did not have a source.properties file
e: file:///Users/mzidek/.pub-cache/hosted/pub.dev/sentry_flutter-7.15.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:39:39 Unresolved reference: SentryFlutter
e: file:///Users/mzidek/.pub-cache/hosted/pub.dev/sentry_flutter-7.15.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:49:21 Unresolved reference: SentryFlutter
```

**Comment by mzdm** [comment] 2024-02-05 15:39
> So `7.14.0` also doesn't work?

Just tried and it does not work

**Comment by buenaflor** [comment] 2024-02-05 15:52
in sentry flutter `7.14.0` we bumped the sentry android sdk from `6.34.0` to `7.0.0`.

please check the breaking changes in the [changelog](https://github.com/getsentry/sentry-java/blob/main/CHANGELOG.md#breaking-changes-1) it may give some hint on why this is happening.

Other than that it'd be great to get a sample app that can reproduce this

**Comment by denrase** [comment] 2024-02-05 17:16
@mzdm Do you have the `ndkVersion` set in your project or `ndk.dir` in your `local.properties`?  Maybe some of the solutions suggested here are of help: https://stackoverflow.com/questions/64372383/ndk-at-library-android-sdk-ndk-bundle-did-not-have-a-source-properties-file

**Comment by tomas-dorda** [comment] 2024-02-09 08:45
After some troubleshooting and modifications to the Android project files, I successfully managed to get the app building again. I had to make these changes:

android/app/build.gradle:
from
```dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6'
    implementation("com.android.support:appcompat-v7:23.2.0")
}
```
to
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
```

android/build.gradle:
`ext.kotlin_version = '1.8.22'` to `ext.kotlin_version = '1.7.10'`

However, upon further testing, I've tried to revert these changes one by one, returning to the project's original configuration. After every change I ran `flutter clean` . Surprisingly, the app continued to build as before, even with the original setup restored. So I guess there could be gradle cache-related problem or something like this?

**Comment by vladislove80** [comment] 2024-02-09 09:35
> After some troubleshooting and modifications to the Android project files, I successfully managed to get the app building again. I had to make these changes:
> 
> android/app/build.gradle: from
> 
> ```
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6'
>     implementation("com.android.support:appcompat-v7:23.2.0")
> }
> ```
> 
> to
> 
> ```
> dependencies {
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
>     implementation 'androidx.appcompat:appcompat:1.6.1'
> }
> ```
> 
> android/build.gradle: `ext.kotlin_version = '1.8.22'` to `ext.kotlin_version = '1.7.10'`
> 
> However, upon further testing, I've tried to revert these changes one by one, returning to the project's original configuration. After every change I ran `flutter clean` . Surprisingly, the app continued to build as before, even with the original setup restored. So I guess there could be gradle cache-related problem or something like this?

the same story. I spent 3 hours trying to solve this issue: changed sentry version in pubspec, change ndk version in gradle, re install android sdk, update kotlin version, clear all caches - nothing helped..

but then I have revert small piece of code in app.dart:

```
  if (!kDebugMode) {
    PlatformDispatcher.instance.onError = (error, stack) {
      Sentry.captureException(error, stackTrace: stack);

      return true;
    };

    Isolate.current.addErrorListener(
      RawReceivePort(
        (error) async {
          final errorAndStacktrace = error as List<dynamic>;
          await Sentry.captureException(
            errorAndStacktrace.first,
            stackTrace: errorAndStacktrace.last,
          );
        },
      ).sendPort,
    );
}
```

I removed this condition and did just:
```

    PlatformDispatcher.instance.onError = (error, stack) {
      Sentry.captureException(error, stackTrace: stack);

      return true;
    };

    Isolate.current.addErrorListener(
      RawReceivePort(
        (error) async {
          final errorAndStacktrace = error as List<dynamic>;
          await Sentry.captureException(
            errorAndStacktrace.first,
            stackTrace: errorAndStacktrace.last,
          );
        },
      ).sendPort,
    );
```

and it woked!!
Ok. but after I rewert this condition to recheck, it didn't break anymore.

BUT now from flutter it works and from android project the same error. if I removed this condition looks like it is working. it is very strange behavior..

p.s. ok guys - flutter clean is an answer.

**Comment by denrase** [comment] 2024-02-12 09:25
@vladislove80 @tomas-dorda Very strange behaviour indeed, hope it was indeed just caching errors and everything works reliably from now on. Closing for now, please report back if the issue arises again. Thank you for the update!

**Closed as completed by denrase** 2024-02-12 09:25 UTC
Labels: Bug

**Comment by adrianvintu** [comment] 2024-04-07 10:37
I deleted

`c:\Users\<USER>\.gradle\caches\`

and 

`c:\Users\<user>\AppData\Local\Pub\Cache\hosted\pub.dev\`

then

`flutter clean` 

and could build again.
