### ISSUE TITLE
`RunZonedGuardedIntegration` cannot be disabled, contrary to Flutter 3.3

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#1003] opened 2022-09-11 14:09 UTC
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

Hi thanks for the wonderful lib! Flutter 3.3 says we should not use runZoneGuarded but should use PlatformDispatcher. However, as is seen in https://github.com/getsentry/sentry-dart/blob/5a6e8fc96dd72607ae666e49f0f04c6454dffc54/dart/lib/src/sentry.dart#L114-L121, seems that RunZonedGuardedIntegration is always there, and cannot be disabled.

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by ueman** [comment] 2022-09-11 14:17
See https://github.com/getsentry/sentry-dart/issues/988#issuecomment-1232135479

If you don't use the appRunner callback, the zone isn't used.

**Comment by fzyzcjy** [comment] 2022-09-11 14:53
Thanks! Documenting it would be quite helpful for other people as well :)

**Comment by marandaneto** [comment] 2022-09-12 07:06
> Thanks! Documenting it would be quite helpful for other people as well :)

We intend to fix it on https://github.com/getsentry/sentry-dart/issues/988 so we don't need to document anything.
I'll close this since it's a very similar/dupe of #988

**Closed as completed by marandaneto** 2022-09-12 07:06 UTC
Labels: Bug
