### ISSUE TITLE
Cannot build appbundle

### ISSUE THREAD

**Issue by MilesAdamson** [getsentry/sentry-dart#257] opened 2020-12-24 21:23 UTC
_Platform:_
- [x]  Flutter Android

_IDE:_
- [x]  IntelliJ/AS

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev

Output of the command `flutter doctor -v` below:
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale en-CA)
    • Flutter version 1.22.5 at C:\Users\miles\flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\miles\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files (x86)\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\miles\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • CLT L04 (mobile) • DXU7N19105001128 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

The version of the SDK:
**4.0.1**

---
I have the following issue:

Cannot build appbundles. I can run in debug mode, and build for iOS, but am having trouble getting an appbundle to build now that I have added this plugin. If I comment out this plugin from my pubspec, and all usages of it, I can build an appbundle just fine.

Here is the failure message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        65.0s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin image_picker...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    1.1s


FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/5.6.2/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jdk1.8.0_211\bin\java.exe -Xmx1536M -Dfile.encoding=windows-1252 -Duser.country=CA -Duser.language=en -Du
ser.variant -cp C:\Users\miles\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2\lib\gradle-launcher-5.6.2.jar org.gradle.launc
her.daemon.bootstrap.GradleDaemon 5.6.2
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


The plugin image_picker could not be built due to the issue above.

```

Now, interestingly it says **image_picker** cannot be built due to an issue above. So instead of removing this plugin, I try removing that one. Then I do that, and get basically the same error for a different plugin:

```
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jdk1.8.0_211\bin\java.exe -Xmx1536M -Dfile.encoding=windows-1252 -Duser.country=CA -Duser.language=en -Du
ser.variant -cp C:\Users\miles\.gradle\wrapper\dists\gradle-6.1.1-all\cfmwm155h49vnt3hynmlrsdst\gradle-6.1.1\lib\gradle-launcher-6.1.1.jar org.gradle.launc
her.daemon.bootstrap.GradleDaemon 6.1.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


The plugin background_fetch could not be built due to the issue above.

```

So now, I remove `background_fetch` and `flutter_background_geolocation`, and try again:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        69.2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
```

It seems like every plugin I have is complaining ever since I added this one. Maybe some of this info will help solve this? I've been trying all day to get an appbundle to work, with different versions of plugins and gradle with no luck.

### build.gradle

```
buildscript {
    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 30                // or higher
        targetSdkVersion    = 30                // or higher
        appCompatVersion    = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.3'
        classpath 'com.google.gms:google-services:4.3.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

### gradle-wrapper.properties

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.3.1-all.zip
```

### grade.properties

```
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=false
```

**Comment by MilesAdamson** [comment] 2020-12-24 21:25
### Dependencies

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bloc: 6.0.3
  http: ^0.12.0+1
  dio: 3.0.9
  fluro: 1.7.2
  flutter_spinkit: ^3.1.0
  flutter_bloc: 6.0.5
  meta: ^1.1.6
  package_info: ^0.4.0+3
  url_launcher: ^5.0.0
  equatable: ^0.2.3
  flutter_secure_storage: ^3.2.0
  json_serializable: ^3.1.0
  signature: ^2.0.0
  intl: 0.16.1
  pull_to_refresh: 1.2.0
  flutter_svg: 0.19.0
  firebase_messaging: 6.0.16
  sentry_flutter: 4.0.1
  google_maps_flutter: ^0.5.21+15
  flutter_background_geolocation: 1.10.1
  permission_handler: 5.0.1+1
  device_info: 0.4.0+2
  firebase_core: ^0.5.0
  cloud_firestore: 0.14.1+3
  firebase_auth: 0.18.1+2
  firebase_storage: 5.0.0
  image_picker:
    git:
      url: https://github.com/cpboyd/plugins.git
      ref: image_picker_workaround
      path: packages/image_picker/image_picker
  photo_view: 0.8.0
  flutter_typeahead: 1.7.0
  retry: 3.0.0+1
  connectivity: 0.4.8+6
  flutter_markdown: ^0.5.0
  firebase_remote_config: 0.3.1+1
  global_configuration: 1.5.0
  flutter_redux: ^0.6.0
  path_provider: 1.6.24
  file_picker: 2.0.12
  open_file: 3.0.3
  uuid: 2.2.2
  community_material_icon: ^5.4.55
  json_at: 1.0.4
```

**Comment by marandaneto** [comment] 2020-12-26 10:17
@MilesAdamson thanks for reporting this.

have you tried to increase the heap size using gradle.properties?

I say that because of `Could not reserve enough space for 1572864KB object heap`
Try to add this to your `gradle.properties`:
https://github.com/getsentry/sentry-java/blob/main/gradle.properties#L2

just out of curiosity, why using Proguard over R8? `android.enableR8=false`, have you tried enabling R8 over Proguard?

Try to run the build using stack trace or info arguments, maybe we get something more useful from there: `Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

I could not reproduce it, our samples just compile it, if one of the suggestions above doesn't work, please create a sample repo where I can reproduce the issue, thanks.

**Comment by MilesAdamson** [comment] 2020-12-29 18:33
Thanks for the reply. I've tried all sorts of combinations of what you have suggested with no luck so far. I will try to make a sample repo for you

**Comment by MilesAdamson** [comment] 2020-12-30 17:25
I made a new project with the exact same pubspec.yaml and couldn't preproduce it either. I decided to [try the other plugin](https://pub.dev/packages/sentry) and everything seems to be working fine. I set the `FlutterError.onError` to log for me so that I still get flutter errors.

You could probably close this, I don't know what you could really do if it can't be reproduced.

So far I had tried lots of stuff (and different combinations of these things)
- changing plugin versions
- changing flutter versions
- enabling R8 over proguard
- increasing the heap size (this one was interesting, it kept asking for more heap size until I got to the maximum you are allowed to allocate and it still wanted more)
- changing gradle version

The only thing that worked was changing to the other plugin. And again, the only thing I couldn't do was build an appdundle. Debug builds worked on android and everything worked on iOS. Very strange

**Comment by marandaneto** [comment] 2021-01-04 08:06
@MilesAdamson thanks for the testing and detailed answer.

our CI even compiles an `appbundle` on every PR https://github.com/getsentry/sentry-dart/blob/main/.github/workflows/flutter.yml#L78

I'll close this as it's not reproducible, if someone else is having the same problem, happy to reopen, thanks.

**Closed as completed by marandaneto** 2021-01-04 08:06 UTC
