### ISSUE TITLE
sentry_dio filtering URL 

### ISSUE THREAD

**Issue by Niggelgame** [getsentry/sentry-dart#1417] opened 2023-05-01 20:30 UTC
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.1 22C65 darwin-arm64,
    locale en-DE)
    • Flutter version 3.7.12 on channel stable at
      /Users/nicolasedelmann/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46
      -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK
    version 32.0.0)
    • Android SDK at /Users/nicolasedelmann/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Users/nicolasedelmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.22
      11.9619390/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nicolasedelmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.22
      11.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nicolasedelmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.22
      11.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nicolasedelmann/Applications/JetBrains
      Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 72.1.5
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nicolasedelmann/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ
      IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Users/nicolasedelmann/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8836.41/IntelliJ
      IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPad Air (5th generation) (mobile) •
      34B941CE-27A9-4666-9E97-2586F9B54119 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)                    • macos
      • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)                       • chrome
      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Version

7.5.0

### Steps to Reproduce

Use a url with `@` in the path with `.addSentry` called on a `Dio` instance. Code example using 
```yaml
dio: ^5.1.1
sentry: ^7.5.0
sentry_flutter: ^7.5.0
sentry_dio: ^7.5.0
```

```dart
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:sentry/sentry.dart';
import 'package:sentry_dio/sentry_dio.dart';

void main() async {
  await Sentry.init((options) {
    options.dsn =
        '';
    options.environment = 'development';
  });

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late Dio dio;

  late Future<Response<Map<String, dynamic>>> fetchFuture;

  @override
  void initState() {
    super.initState();

    dio = Dio();
    dio.addSentry();

    fetchFuture = fetchIt();
  }

  Future<Response<Map<String, dynamic>>> fetchIt() async {
    try {
      return await dio.fetch<Map<String, dynamic>>(Options(
        method: 'GET',
      )
          .compose(
            dio.options,
            '/wishlists/@me',
          )
          .copyWith(baseUrl: 'https://example.com'));
    } catch (e) {
      print(e);
      rethrow;
    }
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      builder: (context, snapshot) {
        return Container();
      },
      future: fetchFuture,
    );
  }
}
``` 

### Expected Result

The request should return with a status code `400`.

### Actual Result

The request fails due to a "FormatException". Logs:

```
flutter: DioError [unknown]: null
Error: FormatException: Invalid character (at character 9)
https://[Filtered]@me
        ^
```

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment] 2023-05-01 21:38
Dupe of https://github.com/getsentry/sentry-dart/issues/1412
We'll cut a release tomorrow.

**Closed as completed by marandaneto** 2023-05-01 21:38 UTC
Labels: Bug
