### ISSUE TITLE
Flutter replay crash on iOS

### ISSUE THREAD

**Issue by danilofuchs** [getsentry/sentry-dart#2314] opened 2024-09-27 13:44 UTC
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

```
[✓] Flutter (Channel stable, 3.24.3, on Pop!_OS 22.04 LTS 6.9.3-76060903-generic,
    locale en_US.UTF-8)
    • Flutter version 3.24.3 on channel stable at /home/danilo/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/danilo/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/local/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can
      be downloaded from https://releases.llvm.org/
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2024.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS
      6.9.3-76060903-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
### Version

8.9.0

### Steps to Reproduce

1. Enable Sentry replays

```dart

    await SentryFlutter.init(
      (options) {
        options.dsn = '';
        options.environment = environmentConfig.environment.name;
        options.release =
            'salvy_app@${packageInfo.version}+${packageInfo.buildNumber}';
        options.captureFailedRequests = false;

        // Do not sample all sessions, only those with errors
        options.experimental.replay.sessionSampleRate = 0.0;
        options.experimental.replay.onErrorSampleRate = 1.0;
      },
    );
```

### Expected Result

Uploads replay

### Actual Result

Crashes

https://salvy.sentry.io/share/issue/65659cde93ac4213836f7c40c79aaf54/

![Image](https://github.com/user-attachments/assets/b929f228-c8be-4a9c-9ced-6af9a16fdbdd)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment] 2024-09-27 20:54
I believe this is the same error that is fixed by this [PR](https://github.com/getsentry/sentry-dart/pull/2306) if I'm not mistaken

This will be part of the next release `8.10.0` which will land early next week

Edit: this is a duplicate of [this](https://github.com/getsentry/sentry-dart/issues/2295), closing this issue

**Closed as not planned** 2024-09-27 20:56 UTC
Labels: Bug, Session Replay
