### ISSUE TITLE
Web missing OS/Device/Browser info

### ISSUE THREAD

**Issue by mnordine** [getsentry/sentry-dart#315] opened 2021-02-23 19:19 UTC
I believe the Sentry javascript client automatically collects and adds os/device/browser info. The Dart web client should do the same.

**Comment by marandaneto** [comment] 2021-02-23 19:41
Kinda dupe of https://github.com/getsentry/sentry-dart/issues/262 but let's keep it open, as we might do for Flutter Web earlier than pure Dart Web

**Closed as completed** 2021-06-15 07:50 UTC
Labels: dart2js
