### ISSUE TITLE
wasm

### ISSUE THREAD

**Issue by zs-dima** [getsentry/sentry-dart#2099] opened 2024-06-13 20:10 UTC
flutter build web --wasm

Leads to the Error:
/home/flutter/.pub-cache/hosted/pub.dev/sentry_flutter-8.2.0/lib/src/native/cocoa/binding.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
56.99 import 'dart:ffi' as ffi;

related issue: https://github.com/getsentry/sentry-dart/issues/2082

### Platform

Flutter Web

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3672], locale en-EN)
    • Flutter version 3.22.2 on channel stable at c:\dev\flutter\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (8 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at 
    • Platform android-34, build-tools 34.0.0
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at 

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at 
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3672]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.142
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[√] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.2.0

### Steps to Reproduce

flutter build web --wasm

### Expected Result

build well

### Actual Result

Error /home/flutter/.pub-cache/hosted/pub.dev/sentry_flutter-8.2.0/lib/src/native/cocoa/binding.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
56.99 import 'dart:ffi' as ffi;

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment] 2024-06-17 09:44
hey, we'll check this out as soon as we can get the pr #2064 going

**Comment by buenaflor** [comment] 2024-06-19 19:14
closing this as a dupe of https://github.com/getsentry/sentry-dart/issues/2082

it's all going to be fixed by the same pr

**Closed as not planned by buenaflor** 2024-06-19 19:14 UTC
Labels: Bug
