### ISSUE TITLE
Issue running on iOS simulator on MacOS Sequoia

### ISSUE THREAD

**Issue by cascalheira** [getsentry/sentry-dart#2096] opened 2024-06-11 10:04 UTC
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.22.2, on macOS 15.0 24A5264n darwin-arm64, locale en-PT)
    • Flutter version 3.22.2 on channel stable at /Users/cascalheira/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cascalheira/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/cascalheira/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/cascalheira/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.3)
    • IntelliJ at /Users/cascalheira/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-242.15523.18)
    • IntelliJ at /Users/cascalheira/Applications/IntelliJ IDEA Ultimate 2024.2 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.91.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.91.20240529

[✓] Connected device (7 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • António’s iPhone (mobile)       • 00008120-001E79300A5BC01E            • ios            • iOS 18.0 22A5282m
    • António’s iPad (mobile)         • 00008103-000615692223001E            • ios            • iOS 18.0 22A5282m
    • iPhone 15 Plus (mobile)         • 793A003E-9447-4E1A-80AB-235EB8324C81 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0 24A5264n darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0 24A5264n darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.2.0

### Steps to Reproduce

Just start the project in the debug mode. There will be an error related to Sentry.

### Expected Result

App should start without errors.

### Actual Result

`Launching lib/main_dev.dart on iPhone 15 Plus in debug mode...
Running Xcode build...
Xcode build done.                                           15.4s
Failed to build iOS app
Semantic Issue (Xcode): No type named 'terminate_handler' in namespace 'std'
/Users/cascalheira/Projects/Hostfully/pmp-mobile/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:59:12

Semantic Issue (Xcode): No member named 'set_terminate' in namespace 'std'
/Users/cascalheira/Projects/Hostfully/pmp-mobile/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:205:46

Semantic Issue (Xcode): No type named 'set_terminate' in namespace 'std'
/Users/cascalheira/Projects/Hostfully/pmp-mobile/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:207:17

Could not build the application for the simulator.
Error launching application on iPhone 15 Plus.`

### Are you willing to submit a PR?

None

**Comment by fodedoumbouya** [comment] 2024-06-11 11:40
same here too

**Comment by chenjie1219** [comment] 2024-06-11 11:48
+1

**Comment by jxstxn1** [comment] 2024-06-11 11:52
The Issue is related with an Issue in the iOS Implementation of Sentry
https://github.com/getsentry/sentry-cocoa/issues/4050

**Comment by buenaflor** [comment] 2024-06-11 12:00
We have to wait for sentry-cocoa to do a release first, I'll ask them for updates (https://github.com/getsentry/sentry-cocoa/pull/4051)

**Comment by kahest** [comment] 2024-06-11 15:37
The [fix in the sentry-cocoa SDK](https://github.com/getsentry/sentry-cocoa/issues/4050) is merged. Please note that it will take a few days to get that released on sentry-cocoa and then dependency bumped and released here as well.

**Comment by fodedoumbouya** [comment] 2024-06-11 16:17
thanks

**Comment by buenaflor** [comment] 2024-06-14 09:29
Quick update, we've merged cocoa 8.29.0. 

The next release oft the Flutter SDK will have this fix ready.

**Comment by clintonksang** [comment] 2024-06-14 09:58
@buenaflor when is that expected? Still in version ^8.2.0

**Comment by buenaflor** [comment] 2024-06-14 11:10
we've got a couple CI problems, I'll try to fix them today but if not then we'll release the next version on Monday

**Comment by 0xvictorb** [comment] 2024-06-17 07:12
@buenaflor Hello, how the release process going?

**Comment by buenaflor** [comment] 2024-06-17 12:23
release is on the way, if everything looks good in ci, this will be out today soon

**Comment by buenaflor** [comment] 2024-06-17 14:33
Sorry for the delay, we've hit another problem in our release system. We recently upgraded our lints to 4.0.0 and they require dart 3.1.0 but our release system is currently configured with 3.0.0. 

When that PR is merged this will be out soon

**Comment by buenaflor** [comment] 2024-06-17 15:13
SDK version `8.3.0` is out, if the problem remains feel free to comment and I'll reopen the issue

**Closed as completed by buenaflor** 2024-06-17 15:13 UTC
Labels: Bug

**Comment by Cypher-O** [comment] 2025-01-12 08:31
Thank you all! I've been struggling with this issue since the release of iOS 18, and I truly appreciate the help

**Comment by michael-timi** [comment] 2025-02-04 19:46
> Thank you all! I've been struggling with this issue since the release of iOS 18, and I truly appreciate the help

please what was the fix for this issue? I encountered just now on MacOS Sequoia

**Comment by buenaflor** [comment] 2025-02-04 19:49
@michael-timi which sentry flutter version are you using?

**Comment by michael-timi** [comment] 2025-02-04 21:55
I've figured it out 
I updated the package to the latest

Thanks for the response btw

**Comment by michael-timi** [comment] 2025-02-04 21:56
> @michael-timi which sentry flutter version are you using?

I've figured it out 
I updated the package to the latest

Thanks for the response btw
