### ISSUE TITLE
Fix `handled` data and differentiate between unhandled errors and crashes

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1116] opened 2022-11-08 19:30 UTC
### Description

From https://github.com/getsentry/rfcs/pull/10#issuecomment-1293729875, emphasis mine:

> The JS SDK team chatted and agreed that as a first step, we will start sending improved (even if not perfect) data somewhere else (TBD where) in the event, so that a) the scale of the problem can be quantified, and b) any backend or UI folks who do eventually pick up that end of the work have example data to work with. (This will likely be somewhere viewable in the JSON but not directly in the UI for the moment, since for now it's really just analytics.)
>
> I'll update here once exactly where and exactly what we'll send is hammered out. **Once we do that, maybe other SDKs can do a similar thing.**

I really would like to see that in the Dart/Flutter SDKs too.

Relates to 
- https://github.com/getsentry/sentry-javascript/issues/6073
- https://github.com/getsentry/sentry-dart/issues/456
- https://github.com/getsentry/rfcs/pull/10

**Comment by marandaneto** [comment] 2022-11-09 07:42
@ueman this is a dupe of https://github.com/getsentry/sentry-dart/issues/456 IMO
Only one SDK needs to have good enough data to understand the problem a bit better, of course the numbers can vary but its still the same thing.
On Flutter side, we can already get this data because we have access to the `mechanism` type, we know that `runZonedGuarded`, `isolateError`, `FlutterError` and `PlatformDispatcher.onError` are unhandled, so its already possible.

**Comment by marandaneto** [comment] 2022-11-09 07:42
@lobsterkatie let me know if you all work on https://github.com/getsentry/sentry-javascript/issues/6073
Maybe we can align this either way.

**Comment by lobsterkatie** [comment] 2022-11-09 18:44
> @ueman this is a dupe of #456 IMO

Is it? That's just about fixing the `handled` value to reflect reality, whereas this is requesting the dart SDK do what the JS SDK is proposing to do and send one of three states.

> @lobsterkatie let me know if you all work on [getsentry/sentry-javascript#6073](https://github.com/getsentry/sentry-javascript/issues/6073) Maybe we can align this either way.

Sounds good. It's in the backlog, but I'm going to push for it to happen since it'd be nice to get the ball rolling on actually finally fixing this stuff!

**Comment by marandaneto** [comment] 2022-11-10 08:21
@lobsterkatie 

> s it? That's just about fixing the handled value to reflect reality, whereas this is requesting the dart SDK do what the JS SDK is proposing to do and send one of three states.

That's what I meant by looking at Dart/Flutter mechanisms, we already know if it's unhandled and it's not properly set as unhandled (we can query that on Looker -> (total events vs unhandled events not marked as unhandled).
So there's no data to gather here, it's either fix it or not.

**Comment by lobsterkatie** [comment] 2022-11-10 20:44
Ah, I see what you're saying. Thanks.

@smeubank - I know there aren't as many dart users as JS users, but good to know that we can already gather some data on this score!

**Comment by marandaneto** [comment] 2023-07-27 08:07
Closed by https://github.com/getsentry/sentry-dart/issues/456
We still have the RFC open https://github.com/getsentry/rfcs/pull/10 and I will follow up with new issues if this goes forward.

**Closed as completed by marandaneto** 2023-07-27 08:07 UTC
