### ISSUE TITLE
getCurrentStackTrace 行 10 在 sentry

### ISSUE THREAD

**Issue by hao1208hao** [getsentry/sentry-dart#2389] opened 2024-11-05 07:18 UTC
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (1 available) 
[✓] Network resources

### Version

8.9.0

### Steps to Reproduce

i don't know 

### Expected Result

nothing

### Actual Result

stacktrace_utils.dart 位置 getCurrentStackTrace 行 10 在 sentry
sentry_client.dart 位置 SentryClient._prepareEvent 行 273 在 sentry
sentry_client.dart 位置 SentryClient.captureEvent 行 119 在 sentry
sentry_client.dart 位置 SentryClient.captureMessage 行 338 在 sentry
hub.dart 位置 Hub.captureMessage 行 226 在 sentry

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment] 2024-11-07 13:08
Hi this is a duplicate of https://github.com/getsentry/sentry-dart/issues/2268

**Closed as not planned by buenaflor** 2024-11-07 13:08 UTC
Labels: Bug
