### ISSUE TITLE
All sentry exceptions come with handled: true

### ISSUE THREAD

**Issue by hmarat** [getsentry/sentry-dart#856] opened 2022-05-06 23:02 UTC
Even if  I do `throw UnimplementedError('Test error message');`, sentry save this with `handled: true` flag. How can I detect and prevent sending errors, which was caught and handled for example in  `try catch`? I tried to do it in `beforeSend` callback, but all events' mechanisms has `handled:  true`.

**Comment by ueman** [comment] 2022-05-07 15:11
This is a duplicate of #456. #456 also describes the reasoning for the behavior.

I've written an event processor, which sets `handled` to `false` at:
https://github.com/ueman/sentry-dart-tools/blob/main/sentry_plus/lib/src/event_processor/unhandled_event_processor.dart

You can use it to mark the uncaught exceptions, though it kinda goes against Sentrys intended usage of it.

**Closed as completed** 2022-05-11 07:25 UTC

**Comment by marandaneto** [comment] 2022-05-11 09:09
The downside of making it `handled: false` is that you are breaking the release health feature https://docs.sentry.io/platforms/flutter/configuration/releases/
So if you do that, I'm not sure that the data would be accurate as it should be since the logic between `errored` session and `crashed` session depends on this flag.
