### ISSUE TITLE
stacktrace_utils.dart 位置 getCurrentStackTrace 行 10 在 sentry

### ISSUE THREAD

**Issue by hao1208hao** [getsentry/sentry-dart#2267] opened 2024-09-04 03:28 UTC
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4
    23E214 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.22.2 on channel stable at
      /Users/pengsanyuan/Documents/flutter/flutter-sdk
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 个月前), 2024-06-05
      22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror
      https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices
    (Android SDK version 34.0.0)
    • Android SDK at
      /Users/pengsanyuan/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install
      "cmdline-tools;latest"`
      See
      https://developer.android.com/studio/command-line
      for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept
      the SDK licenses.
      See
      https://flutter.dev/docs/get-started/install/maco
      s#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

### Version

8.7.0

### Steps to Reproduce

不知道怎么出现的

### Expected Result

正常收集异常信息

### Actual Result

stacktrace_utils.dart 位置 getCurrentStackTrace 行 10 在 sentry

Hide 4 more frames
sentry_client.dart 位置 SentryClient._prepareEvent 行 270 在 sentry
sentry_client.dart 位置 SentryClient.captureEvent 行 117 在 sentry
sentry_client.dart 位置 SentryClient.captureMessage 行 335 在 sentry
hub.dart 位置 Hub.captureMessage 行 226 在 sentry

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment] 2024-09-04 12:28
This is a duplicate of https://github.com/getsentry/sentry-dart/issues/2268

**Closed as not planned by buenaflor** 2024-09-04 12:28 UTC
Labels: Bug
